// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45C8OKpo7lW_ikQJQbg7eDxtPyUzVLIY',
    appId: '1:1008435332908:web:2b847bb674d0bc5cbbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    authDomain: 'beauty-user.firebaseapp.com',
    storageBucket: 'beauty-user.firebasestorage.app',
    measurementId: 'G-VLNWGDCBCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA717oQJvOAioo9KAStmwWWvKOT9RoOGsk',
    appId: '1:1008435332908:android:da8880c87ed99390bbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    storageBucket: 'beauty-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4S3bPo_GqwoCrJ81I1BLKtMU5eP6sVWE',
    appId: '1:1008435332908:ios:d8d68796b7a0c5aebbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    storageBucket: 'beauty-user.firebasestorage.app',
    iosBundleId: 'com.beautyuser.bayanatz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4S3bPo_GqwoCrJ81I1BLKtMU5eP6sVWE',
    appId: '1:1008435332908:ios:6e1615c2b2856c97bbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    storageBucket: 'beauty-user.firebasestorage.app',
    iosBundleId: 'com.example.beautyUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA45C8OKpo7lW_ikQJQbg7eDxtPyUzVLIY',
    appId: '1:1008435332908:web:a03b6b7c103c5b2ebbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    authDomain: 'beauty-user.firebaseapp.com',
    storageBucket: 'beauty-user.firebasestorage.app',
    measurementId: 'G-E6SLP2KCYT',
  );
}
